name: Pulumi Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      PULUMI_ACCESS_TOKEN:  ${{ secrets.PULUMI_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Pulumi deploy
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: ${{ secrets.PULUMI_STACK_NAME }}
    
